In [1]:
#using Pkg
#Pkg.add("ScikitLearn")

In [2]:
#using Pkg
#Pkg.add("CSV")

In [3]:
#using Pkg
#Pkg.add("DataFrames")

In [4]:
#using Pkg
#Pkg.add("XLSX")

In [5]:
using ScikitLearn,CSV,DataFrames

In [6]:
df= CSV.read("IRIS.csv", DataFrame)
first(df,5)

5×5 DataFrame
 Row │ sepal_length  sepal_width  petal_length  petal_width  species     
     │ Float64       Float64      Float64       Float64      String15    
─────┼───────────────────────────────────────────────────────────────────
   1 │          5.1          3.5           1.4          0.2  Iris-setosa
   2 │          4.9          3.0           1.4          0.2  Iris-setosa
   3 │          4.7          3.2           1.3          0.2  Iris-setosa
   4 │          4.6          3.1           1.5          0.2  Iris-setosa
   5 │          5.0          3.6           1.4          0.2  Iris-setosa

In [7]:
# Format
# CSV.File(filename;drop=["colulm1", "column2"....., column n])
# Format for select command
# CSV.File(file; select=[column1, column2])

In [8]:
df=Matrix(df)

150×5 Matrix{Any}:
 5.1  3.5  1.4  0.2  "Iris-setosa"
 4.9  3.0  1.4  0.2  "Iris-setosa"
 4.7  3.2  1.3  0.2  "Iris-setosa"
 4.6  3.1  1.5  0.2  "Iris-setosa"
 5.0  3.6  1.4  0.2  "Iris-setosa"
 5.4  3.9  1.7  0.4  "Iris-setosa"
 4.6  3.4  1.4  0.3  "Iris-setosa"
 5.0  3.4  1.5  0.2  "Iris-setosa"
 4.4  2.9  1.4  0.2  "Iris-setosa"
 4.9  3.1  1.5  0.1  "Iris-setosa"
 5.4  3.7  1.5  0.2  "Iris-setosa"
 4.8  3.4  1.6  0.2  "Iris-setosa"
 4.8  3.0  1.4  0.1  "Iris-setosa"
 ⋮                   
 6.0  3.0  4.8  1.8  "Iris-virginica"
 6.9  3.1  5.4  2.1  "Iris-virginica"
 6.7  3.1  5.6  2.4  "Iris-virginica"
 6.9  3.1  5.1  2.3  "Iris-virginica"
 5.8  2.7  5.1  1.9  "Iris-virginica"
 6.8  3.2  5.9  2.3  "Iris-virginica"
 6.7  3.3  5.7  2.5  "Iris-virginica"
 6.7  3.0  5.2  2.3  "Iris-virginica"
 6.3  2.5  5.0  1.9  "Iris-virginica"
 6.5  3.0  5.2  2.0  "Iris-virginica"
 6.2  3.4  5.4  2.3  "Iris-virginica"
 5.9  3.0  5.1  1.8  "Iris-virginica"

In [9]:
iris_x= convert(Array,df[:,[1,2,3,4]]);
iris_y= convert(Array,df[:,[5]]);

# LOGISTICS REGRESSION

In [10]:
@sk_import linear_model: LogisticRegression

PyObject <class 'sklearn.linear_model._logistic.LogisticRegression'>

In [11]:
log_reg_model = LogisticRegression()

PyObject LogisticRegression()

In [12]:
fit!(log_reg_model,iris_x,iris_y)

C:\Users\karth\.julia\conda\3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


PyObject LogisticRegression()

In [13]:
predictions= predict(log_reg_model,iris_x)

150-element Vector{Any}:
 "Iris-setosa"
 "Iris-setosa"
 "Iris-setosa"
 "Iris-setosa"
 "Iris-setosa"
 "Iris-setosa"
 "Iris-setosa"
 "Iris-setosa"
 "Iris-setosa"
 "Iris-setosa"
 "Iris-setosa"
 "Iris-setosa"
 "Iris-setosa"
 ⋮
 "Iris-virginica"
 "Iris-virginica"
 "Iris-virginica"
 "Iris-virginica"
 "Iris-virginica"
 "Iris-virginica"
 "Iris-virginica"
 "Iris-virginica"
 "Iris-virginica"
 "Iris-virginica"
 "Iris-virginica"
 "Iris-virginica"

In [14]:
@sk_import metrics:accuracy_score

PyObject <function accuracy_score at 0x00000000982CEDC0>

In [15]:
accuracy=accuracy_score(predictions,iris_y)

0.9733333333333334

# DECISION TREE

In [16]:
@sk_import tree: DecisionTreeClassifier

PyObject <class 'sklearn.tree._classes.DecisionTreeClassifier'>

In [17]:
tree_model= DecisionTreeClassifier()

PyObject DecisionTreeClassifier()

In [18]:
fit!(tree_model,iris_x,iris_y)

PyObject DecisionTreeClassifier()

In [19]:
tree_predictions= predict(tree_model,iris_x)

150-element Vector{Any}:
 "Iris-setosa"
 "Iris-setosa"
 "Iris-setosa"
 "Iris-setosa"
 "Iris-setosa"
 "Iris-setosa"
 "Iris-setosa"
 "Iris-setosa"
 "Iris-setosa"
 "Iris-setosa"
 "Iris-setosa"
 "Iris-setosa"
 "Iris-setosa"
 ⋮
 "Iris-virginica"
 "Iris-virginica"
 "Iris-virginica"
 "Iris-virginica"
 "Iris-virginica"
 "Iris-virginica"
 "Iris-virginica"
 "Iris-virginica"
 "Iris-virginica"
 "Iris-virginica"
 "Iris-virginica"
 "Iris-virginica"

In [20]:
accuracy_score(tree_predictions,iris_y)

1.0

# RANDOM FOREST

In [21]:
@sk_import ensemble: RandomForestClassifier

PyObject <class 'sklearn.ensemble._forest.RandomForestClassifier'>

In [22]:
RF_model= DecisionTreeClassifier()

PyObject DecisionTreeClassifier()

In [23]:
fit!(RF_model,iris_x,iris_y)

PyObject DecisionTreeClassifier()

In [24]:
RF_predictions= predict(RF_model,iris_x)

150-element Vector{Any}:
 "Iris-setosa"
 "Iris-setosa"
 "Iris-setosa"
 "Iris-setosa"
 "Iris-setosa"
 "Iris-setosa"
 "Iris-setosa"
 "Iris-setosa"
 "Iris-setosa"
 "Iris-setosa"
 "Iris-setosa"
 "Iris-setosa"
 "Iris-setosa"
 ⋮
 "Iris-virginica"
 "Iris-virginica"
 "Iris-virginica"
 "Iris-virginica"
 "Iris-virginica"
 "Iris-virginica"
 "Iris-virginica"
 "Iris-virginica"
 "Iris-virginica"
 "Iris-virginica"
 "Iris-virginica"
 "Iris-virginica"

In [25]:
accuracy_score(RF_predictions,iris_y)

1.0

---

# with TRAIN-TEST SPLIT

In [26]:
@sk_import model_selection: train_test_split

┌ Warning: Module model_selection has been ported to Julia - try `import ScikitLearn: CrossValidation` instead
└ @ ScikitLearn.Skcore C:\Users\karth\.julia\packages\ScikitLearn\ssekP\src\Skcore.jl:179


PyObject <function train_test_split at 0x00000000982914C0>

In [27]:
x_train,x_test,y_train,y_test= train_test_split(iris_x,iris_y,test_size=0.2,random_state=1)

4-element Vector{Matrix}:
 [6.1 3.0 4.6 1.4; 7.7 3.0 6.1 2.3; … ; 6.7 3.1 5.6 2.4; 4.9 3.1 1.5 0.1]
 [5.8 4.0 1.2 0.2; 5.1 2.5 3.0 1.1; … ; 6.1 2.8 4.7 1.2; 6.3 2.5 5.0 1.9]
 ["Iris-versicolor"; "Iris-virginica"; … ; "Iris-virginica"; "Iris-setosa";;]
 ["Iris-setosa"; "Iris-versicolor"; … ; "Iris-versicolor"; "Iris-virginica";;]

In [28]:
log_reg_model2 = LogisticRegression()

PyObject LogisticRegression()

In [29]:
fit!(log_reg_model2,x_train,y_train)

┌ Warning: `vendor()` is deprecated, use `BLAS.get_config()` and inspect the output instead
│   caller = npyinitialize() at numpy.jl:67
└ @ PyCall C:\Users\karth\.julia\packages\PyCall\L0fLP\src\numpy.jl:67
C:\Users\karth\.julia\conda\3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


PyObject LogisticRegression()

In [30]:
predictions2= predict(log_reg_model2,x_test)

30-element Vector{Any}:
 "Iris-setosa"
 "Iris-versicolor"
 "Iris-versicolor"
 "Iris-setosa"
 "Iris-virginica"
 "Iris-versicolor"
 "Iris-virginica"
 "Iris-setosa"
 "Iris-setosa"
 "Iris-virginica"
 "Iris-versicolor"
 "Iris-setosa"
 "Iris-virginica"
 ⋮
 "Iris-setosa"
 "Iris-setosa"
 "Iris-versicolor"
 "Iris-versicolor"
 "Iris-virginica"
 "Iris-setosa"
 "Iris-virginica"
 "Iris-versicolor"
 "Iris-setosa"
 "Iris-setosa"
 "Iris-versicolor"
 "Iris-virginica"

In [31]:
accuracy_score(predictions2,y_test)

0.9666666666666667